project:
  type: website
  output-dir: docs

website:
  title: "Governos Brasileiros 1995–2025"
  description: "Análise histórica e econômica dos governos presidenciais brasileiros"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Governos"
        menu:
          - text: "Fernando H. Cardoso (1995–2003)"
            href: fernando_hc.qmd
          - text: "Lula I (2003–2011)"
            href: lula_mandato.qmd
      - text: "Sobre"
        href: "about.qmd"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    lang: pt-BR
