---
title: "O Governo Dilma: Intervencionismo Estatal e Instabilidade Política"
format: html
---
## Introdução

# A Inflação (IPCA)
```{r}
#| echo: false
#| message: false
#| warning: false
library(rbcb)
library(magrittr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(readxl)
library(here)
library(janitor)


dados_inflacao <- read_excel(here("planilhaIPCA/ipca.xls"))
dados_dilma <- dados_inflacao %>% 
  clean_names() %>% 
  rename(
    ano= 1,
    mes_nome=2,
    numero_indice=3,
    ipca_trimestral=5
  ) |>
  fill(ano, .direction = "down")
dados_dilma <- dados_dilma %>% 
  mutate(numero_indice= as.numeric(gsub(",",".", numero_indice)),
         ipca_trimestral= as.numeric(gsub(",",".", ipca_trimestral))
         )%>% 
  filter(ano>2010 & ano<2017) %>% 
 mutate(
   mes_num = case_when(
      mes_nome == "JAN" ~ "01", mes_nome == "FEV" ~ "02", mes_nome == "MAR" ~ "03",
      mes_nome == "ABR" ~ "04", mes_nome == "MAI" ~ "05", mes_nome == "JUN" ~ "06",
      mes_nome == "JUL" ~ "07", mes_nome == "AGO" ~ "08", mes_nome == "SET" ~ "09",
      mes_nome == "OUT" ~ "10", mes_nome == "NOV" ~ "11", mes_nome == "DEZ" ~ "12"
    ),
    data_final = as.Date(paste(ano, mes_num, "01", sep = "-"))
 ) 

ggplot(dados_dilma, aes(x= data_final, y= ipca_trimestral)) +
  geom_line( color= "#302681", size= 1.2)+
  scale_x_date(date_breaks = "1 year", date_labels ="%Y")+
  scale_y_continuous(labels = function(x)paste0(x,"%"))+
  labs(
    title = "Comportamento do IPCA no Governo Dilma (2011–2016)",
    subtitle = "Dados Oficiais do banco do Brasil",
    x = "Ano",
    y = "Variação trimestral %",
    caption = "Fonte:Banco Central do Brasil/ SGS",
  )+
  theme_minimal()+
theme(legend.position = "bottom")
```









# Câmbio
```{r}
#| echo: false
#| message: false
#| warning: false
dados_dolar <- get_series(3697, start_date="2011-01-01", end_date = "2016-05-12")
names(dados_dolar)[2] <- "value"
dados_china <- get_series(21631, start_date = "2011-01-01",end_date = "2016-05-12")
names(dados_china)[2] <- "value"
dados_euro<- get_series(21619, start_date= "2011-01-01", end_date= "2016-05-12")
names(dados_euro)[2] <- "value"
 dados_moedas <- dados_dolar %>% 
 inner_join(dados_china,by= "date",suffix = c("_dolar","_china")) %>% 
  inner_join(dados_euro,by="date")
 
 names(dados_moedas) <- c("Data","Dolar","Yuan","Euro")
 dados_grafdilma <- dados_moedas %>% pivot_longer(cols = c(Dolar,Yuan,Euro), names_to = "Moeda" , values_to = "Taxa")
 ggplot(dados_grafdilma,aes(x=Data,y=Taxa,color=Moeda))+
   geom_line(size=1)+
   scale_x_date(date_breaks = "1 year", date_labels ="%Y")+
  scale_y_continuous(labels = function(x)paste0(x,"R$"))+
  
  labs(
    title = "Evolução da Taxa de Câmbio no Governo Dilma",
    subtitle = "",
    x= "Ano",
    y= "preçoem Real(R$)",
    fill="Regime Cambial",
    color= "Regime Cambial",
    caption = "Fonte:Banco Central/SGS"
  )+
  theme_minimal()+
theme(legend.position = "bottom")
```


# A Taxa Selic
```{r}
#| echo: false
#| message: false
#| warning: false


dados_selic_dilma <- get_series(4189, start_date = "2011-01-01", end_date = "2016-05-12")
names(dados_selic_dilma)[2] <- "Selic"
names(dados_selic_dilma)[1] <- "Anos"
ggplot(dados_selic_dilma, aes(x= Anos, y = Selic))+
  geom_line(color= "#ffc222",size=1.2)+
  scale_x_date(date_breaks = "1 year", date_labels ="%Y")+
  scale_y_continuous(labels = function(x)paste0(x,"%"))+
  labs(
    title = "Selic: A Nova Matriz Econômica e o Repique dos Juros",
    subtitle = "O impacto dos juros na economia nos anos (2011-2016)",
    x= "Taxa Selic",
    y= "Ano",
    caption = "Fonte: Banco do Central/ SGS"
  )+
  theme_minimal()+
  theme(legend.position = "bottom")
```

